import { Product } from "@/components/product-card";

export const products: Product[] = [
  {
    id: 1,
    name: "Aloe Vera Gel",
    sizes: ["100gm"],
    prices: [199],
    image: [
      "/about/aloe1.jpg",
      "/about/aloe2.jpg",
      "/about/aloe3.jpg",
      "/about/aloe4.jpg",
      "/about/aloe5.jpg",
      "/about/aloe6.jpg",
      "/about/aloe7.jpg",
    ],
    category: "skincare",
  },
  {
    id: 2,
    name: "Hibiscus Powder",
    sizes: ["50gm", "100gm", "200gm"],
    prices: [99, 149, 199],
    image: [
      "/about/hibiscus1.jpg",
      "/about/hibiscus2.jpg",
      "/about/hibiscus3.jpg",
      "/about/hibiscus4.jpg",
      "/about/hibiscus5.jpg",
      "/about/hibiscus6.jpg",
      "/about/hibiscus7.jpg"
    ],
    category: "haircare",
  },
  {
    id: 3,
    name: "Chamomile Powder",
    sizes: ["50gm", "100gm", "200gm"],
    prices: [109, 199, 289],
    image: ["/about/Chamomile1.jpg",
      "/about/Chamomile2.jpg",
      "/about/Chamomile3.jpg",
      "/about/Chamomile4.jpg",
      "/about/Chamomile5.jpg",
      "/about/Chamomile6.jpg",
      "/about/Chamomile7.jpg",
    ],
    category: "skincare",
  },
  {
    id: 4,
    name: "Butterfly Pea Powder",
    sizes: ["50gm", "100gm", "200gm"],
    prices: [149, 229, 309],
    image: ["/about/Butterfly1.jpg",
      "/about/Butterfly2.jpg",
      "/about/Butterfly3.jpg",
      "/about/Butterfly4.jpg",
      "/about/Butterfly5.jpg",
      "/about/Butterfly6.jpg",
      "/about/Butterfly7.jpg",
    ],
    category: "haircare",
  },
  {
    id: 5,
    name: "Moringa Powder",
    sizes: ["50gm", "100gm", "200gm"],
    prices: [99, 149, 199],
    image: ["/about/Moringa1.jpg",
      "/about/Moringa2.jpg",
      "/about/Moringa3.jpg",
      "/about/Moringa4.jpg",
      // "/about/Moringa5.jpg",
      // "/about/Moringa6.jpg",
      // "/about/Moringa7.jpg"
    ],
    category: "skincare",
  },
  {
    id: 6,
    name: "Senna Leaves",
    sizes: ["100gm", "200gm"],
    prices: [149, 199],
    image: ["/about/Senna1.jpg",
      "/about/Senna2.jpg",
      "/about/Senna3.jpg",
      "/about/Senna4.jpg",
      "/about/Senna5.jpg",
      "/about/Senna6.jpg",
      // "/about/Senna7.jpg",
    ],
    category: "haircare",
  },
  {
    id: 7,
    name: "Goat milk white soap",
    sizes: ["100gm"],
    prices: [199],
    image: ["/about/goatmilk1.jpg",
      "/about/goatmilk2.jpg",
      "/about/goatmilk3.jpg",
      "/about/goatmilk4.jpg",
      "/about/goatmilk5.jpg",
      "/about/goatmilk6.jpg",
      "/about/goatmilk7.jpg"
    ],
    category: "soaps",
  },
  {
    id: 8,
    name: "Neem Soap",
    sizes: ["100gm"],
    prices: [199],
    image: ["/about/Neem1.jpg",
      "/about/Neem2.jpg",
      "/about/Neem3.jpg",
      "/about/Neem4.jpg",
      "/about/Neem5.jpg",
      "/about/Neem6.jpg",
      "/about/Neem7.jpg"

    ],
    category: "soaps",
  },
  {
    id: 9,
    name: "Nettle Soap",
    sizes: ["100gm"],
    prices: [229],
    image: ["/about/Nettle1.jpg",
      "/about/Nettle2.jpg",
      "/about/Nettle3.jpg",
      "/about/Nettle4.jpg",
      "/about/Nettle5.jpg",
      "/about/Nettle6.jpg",
      "/about/Nettle7.jpg"
    ],
    category: "soaps",
  },
  {
    id: 10,
    name: "Manjistha & Coconut Soap",
    sizes: ["100gm"],
    prices: [229],
    image: ["/about/Manjistha1.jpg",
      "/about/Manjistha2.jpg",
      "/about/Manjistha3.jpg",
      "/about/Manjistha4.jpg",
      "/about/Manjistha5.jpg",
      "/about/Manjistha6.jpg",
      "/about/Manjistha7.jpg",
    ],
    category: "soaps",
  },
  {
    id: 11,
    name: "Red Clay Soap",
    sizes: ["100gm"],
    prices: [229],
    image: ["/about/RedClay1.jpg",
      "/about/RedClay2.jpg",
      "/about/RedClay3.jpg",
      "/about/RedClay4.jpg",
      "/about/RedClay5.jpg",
      "/about/RedClay6.jpg",
      "/about/RedClay7.jpg",

    ],
    category: "soaps",
  },
  {
    id: 12,
    name: "Shea Butter",
    sizes: ["100gm", "200gm", "500gm"],
    prices: [199, 389, 949],
    image: ["/about/sheabutter.jpg"],
    category: "skincare",
  },
];