import { Product } from "@/components/product-card";

export const products: Product[] = [
  {
    id: 1,
    name: "Aloe Vera Gel",
    sizes: ["100gm"],
    prices: [199],
    image: "about/aloevera.jpg",
    category: "skincare",
  },
  {
    id: 2,
    name: "Hibiscus Powder",
    sizes: ["50gm", "100gm", "200gm"],
    prices: [99, 149, 199],
    image: "about/hibiscus.jpg",
    category: "haircare",
  },
  {
    id: 3,
    name: "Chamomile Powder",
    sizes: ["50gm", "100gm", "200gm"],
    prices: [109, 199, 289],
    image: "about/Chamomile.jpg",
    category: "skincare",
  },
  {
    id: 4,
    name: "Butterfly Pea Powder",
    sizes: ["50gm", "100gm", "200gm"],
    prices: [149, 229, 309],
    image: "about/Butterfly.jpg",
    category: "haircare",
  },
  {
    id: 5,
    name: "Moringa Powder",
    sizes: ["50gm", "100gm", "200gm"],
    prices: [99, 149, 199],
    image: "about/Moringa.jpg",
    category: "skincare",
  },
  {
    id: 6,
    name: "Senna Leaves",
    sizes: ["100gm", "200gm"],
    prices: [149, 199],
    image: "about/Senna.jpg",
    category: "haircare",
  },
  {
    id: 7,
    name: "Goat milk white soap",
    sizes: ["100gm"],
    prices: [199],
    image: "about/goatmilk1.jpg",
    category: "soaps",
  },
  // {
  //   id: 7,
  //   name: "Goat Milk White Soap",
  //   sizes: ["100gm"],
  //   prices: [199],
  //   image: "about/goatmilk.jpg",
  //   category: "soaps",
  // },
  {
    id: 8,
    name: "Neem Soap",
    sizes: ["100gm"],
    prices: [199],
    image: "about/Neem.jpg",
    category: "soaps",
  },
  {
    id: 9,
    name: "Nettle Soap",
    sizes: ["100gm"],
    prices: [229],
    image: "about/Nettle.jpg",
    category: "soaps",
  },
  {
    id: 10,
    name: "Manjistha & Coconut Soap",
    sizes: ["100gm"],
    prices: [229],
    image: "about/Manjistha.jpg",
    category: "soaps",
  },
  {
    id: 11,
    name: "Red Clay Soap",
    sizes: ["100gm"],
    prices: [229],
    image: "about/Redclay.jpg",
    category: "soaps",
  },
  {
    id: 12,
    name: "Shea Butter",
    sizes: ["100gm", "200gm", "500gm"],
    prices: [199, 389, 949],
    image: "about/sheabutter.jpg",
    category: "skincare",
  },
];
